brain_two/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path, include
from .views import TodoListView, TodoListDetail, TodoListCreateView, TodoListUpdateView, TodoListDeleteView, TodoItemCreateView, TodoItemUpdateView
from .models import TodoList

app_name = 'todos'

urlpatterns = [
    path('', TodoListView.as_view(), name='todo_list_list'),
    path('create/', TodoListCreateView.as_view(), name='todo_list_create'),
    path('<int:pk>/', TodoListDetail.as_view(), name='todo_list_detail'),
    path('<int:pk>/edit/', TodoListUpdateView.as_view(), name='todo_list_update'),
    path('<int:pk>/delete/', TodoListDeleteView.as_view(), name='todo_list_delete'),
    path('items/create/<int:pk>/', TodoItemCreateView.as_view(), name='todo_item_create'),
    path('items/<int:pk>/edit/', TodoItemUpdateView.as_view(), name='todo_item_update'),
]

todos/models.py
from django.db import models




# Create your models here.

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList,
        on_delete=models.CASCADE,
        related_name="items"
    )

    def __str__(self):
        return self.task

todos/forms.py
from django import forms
from .models import TodoList, TodoItem

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name']

class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['task', 'due_date', 'is_completed']

todos/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import TodoItem, TodoList
from .forms import TodoListForm, TodoItemForm
from django.urls import reverse

class TodoListView(ListView):
    model = TodoList
    template_name = 'todos/todo_list.html'
    context_object_name = 'todo_lists'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todo_list'] = self.get_queryset().first()
        return context

class TodoListDetail(DetailView):
    model = TodoList
    template_name = 'todos/todo_list_detail.html'
    context_object_name = 'todolist'

class TodoListCreateView(CreateView):
    model = TodoList
    form_class = TodoListForm
    template_name = 'todos/todo_list_create.html'
    success_url = '/todos/'

class TodoListUpdateView(UpdateView):
    model = TodoList
    form_class = TodoListForm
    template_name = 'todos/todo_list_update.html'
    context_object_name = 'todolist'

    def get_success_url(self):
        return reverse('todos:todo_list_detail', kwargs={'pk': self.object.pk})

class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = 'todos/todo_list_delete.html'
    success_url = '/todos/'

class TodoItemCreateView(CreateView):
    model = TodoItem
    form_class = TodoItemForm
    template_name = 'todos/todo_item_create.html'

    def form_valid(self, form):
        form.instance.list_id = self.kwargs['pk']
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('todos:todo_list_detail', kwargs={'pk': self.kwargs['pk']})
    
class TodoItemUpdateView(UpdateView):
    model = TodoItem
    form_class = TodoItemForm
    template_name = 'todos/todo_item_update.html'

    def get_success_url(self):
        return reverse('todos:todo_list_detail', kwargs={'pk': self.object.list.pk})

todos/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

todos/templates/todos/todo_item_create.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <h1>Create a new item</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
{% endblock %}

todos/templates/todos/todo_item_update.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Update Item</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
</main>
{% endblock %}

todos/templates/todos/todo_list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
        <p><a href="{% url 'todos:todo_list_create' %}">Create a new list</a></p>
        <p><a href="{% url 'todos:todo_item_create' todo_list.pk %}">Create a new item</a></p>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of items</th>
                </tr>
            </thead>
            <tbody>
                {% for todo_list in todo_lists %}
                <tr>
                    <td><a href="{% url 'todos:todo_list_detail' pk=todo_list.pk %}">{{ todo_list.name }}</a></td>
                    <td>{{ todo_list.items.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

todos/templates/todos/todo_list_create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create a new list</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>
{% endblock %}

todos/templates/todos/todo_list_delete.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Are you sure?</h1>
        <form method="post">
            {% csrf_token %}
            <button>Delete</button>
        </form>
    </div>
</main>
{% endblock %}

todos/templates/todos/todo_list_detail.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>{{ todolist.name }}</h1>
        <p>Number of items: {{ todolist.items.count }}</p>
        <p><a href="{% url 'todos:todo_item_create' pk=todolist.pk %}">Create a new item</a></p>
        <p><a href="{% url 'todos:todo_list_update' pk=todolist.pk %}">Edit</a> | <a href="{% url 'todos:todo_list_delete' pk=todolist.pk %}">Delete</a></p>
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for item in todolist.items.all %}
                <tr>
                    <td><a href="{% url 'todos:todo_item_update' pk=item.pk %}">{{ item.task }}</a></td>
                    <td>{{ item.due_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

todos/templates/todos/todo_list_update.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Update List</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
</main>
{% endblock %}